Install git before int tests

diff --git a/.ci/dev_integration_test b/.ci/dev_integration_test
--- a/.ci/dev_integration_test
+++ b/.ci/dev_integration_test
@@ -24,6 +24,8 @@ if [[ $TARGET_CLUSTER == "" ]]; then
     exit 1
 fi
 
+apk update
+
 if ! command -v curl &> /dev/null
 then
     apk add --no-cache --no-progress curl openssl apache2-utils
@@ -34,6 +36,13 @@ then
     echo "Python3 could not be found"
     echo "Try installing it..."
     apk add --no-cache --no-progress python3 python3-dev py3-pip gcc libc-dev libffi-dev openssl-dev cargo build-base
+fi
+
+if ! command -v git &> /dev/null
+then
+    echo "git could not be found"
+    echo "Try installing it..."
+    apk add add --no-cache --no-progress git
 fi
 
 if ! command -v helm &> /dev/null
