Update to golang:1.23.4--alpine3.21

diff --git a/.ci/dev_integration_test b/.ci/dev_integration_test
--- a/.ci/dev_integration_test
+++ b/.ci/dev_integration_test
@@ -31,19 +31,19 @@ then
     apk add --no-cache --no-progress curl openssl apache2-utils
 fi
 
-if ! command -v python3 &> /dev/null
-then
-    echo "Python3 could not be found"
-    echo "Try installing it..."
-    apk add --no-cache --no-progress python3 python3-dev py3-pip gcc libc-dev libffi-dev openssl-dev cargo build-base
-fi
-
 if ! command -v git &> /dev/null
 then
     echo "git could not be found"
     echo "Try installing it..."
     apk add --no-cache --no-progress git
     git --version
+fi
+
+if ! command -v python3 &> /dev/null
+then
+    echo "Python3 could not be found"
+    echo "Try installing it..."
+    apk add --no-cache --no-progress python3 python3-dev py3-pip gcc libc-dev libffi-dev openssl-dev cargo build-base
 fi
 
 if ! command -v helm &> /dev/null
